version: 0.0

os: linux

files:
  - source: /
    destination: /demo-app

hooks:
  BeforeInstall:
    - location: scripts/beforeinstall.sh
      timeout: 300
      runas: root
      
  AfterInstall:
    - location: scripts/afterinstall.sh
      timeout: 1000
      runas: root
      
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
